name: Draft Release Notes

on:
  workflow_dispatch:

jobs:
  draft-stable:
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the requested branch
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow
      - name: Cache Tools
        uses: actions/cache@2b250bc32ad02700b996b496c14ac8c2840a2991 # v2.1.8
        with:
          path: tools
          key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}
      - name: Set up git version
        if: ${{ !contains(github.ref, '/hotfix/') && !contains(github.ref, '/release/') }}
        uses: gittools/actions/gitversion/setup@a91d2e8b65fa493e04e072c115068cbd4a6f03f8 # v0.9.9
        with:
          versionSpec: "5.x"
      - name: Run git version
        if: ${{ !contains(github.ref, '/hotfix/') && !contains(github.ref, '/release/') }}
        id: gitversion
        uses: gittools/actions/gitversion/execute@a91d2e8b65fa493e04e072c115068cbd4a6f03f8 # v0.9.9
      - name: Create release branch ${{ github.event.inputs.version }}
        if: ${{ steps.gitversion.outputs.majorMinorPatch }}
        run: git switch -c release/${{ steps.gitversion.outputs.majorMinorPatch }}
      - name: Push new branch
        if: ${{ steps.gitversion.outputs.majorMinorPatch }}
        uses: ad-m/github-push-action@d91a481090679876dfc4178fef17f286781251df # v0.8.0
        with:
          branch: "release/${{ steps.gitversion.outputs.majorMinorPatch }}"
          github_token: ${{ secrets.GH_TOKEN }}
      - name: Drafting Release Notes
        uses: cake-build/cake-action@a6eb054329257c9e70a6c6bf01747ad6e1d9d52b # v1
        with:
          script-path: recipe.cake
          target: releasenotes
          verbosity: Diagnostic
          cake-version: 0.38.5
          cake-bootstrap: true